config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => "user/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'settings', to: 'welcome#setting'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  resources :user_stocks, only: [:create, :destroy, :index]
  resources :friendships
  resources :users, only:[:show]
  post 'add_friends',to: 'users#add_friend'
  get 'my_friends', to: 'users#my_friends'
  post 'accept_request', to: 'users#accept_request'
  post 'reject_request', to: 'users#reject_request'
  resources :profiles, only: [:create,:update,:edit,:new]
  resources :educations, only:[:create,:update,:edit,:new]
end

app/views/friends/_frndresult.html.erb
<% if params[:action] == 'search'%>
	<div class="result-flash-block col-md-12">
		<%= bootstrap_flash %>
	</div>
<% end %>
<% if @users %>
	<% @users.each do |frnd|%>
		<% if frnd != current_user %>
			<div class="well col-md-3 padclass">
				<b>
					<% if frnd.has_image? %>
							<%= image_tag(frnd.images.last.picture.url, size: "40x40") %>
					<% else %>
							<%= image_tag("default.jpg", size: "40x40")%>
					<% end %><%= frnd.fullName%>
				</b>
				<br />
				<%if current_user.friends.include?(frnd)%>
					<button type="button" class="btn btn-xs btn-default disabled"><i class="fa fa-user-plus"></i> &nbsp;Aleard Friends</button>
				<% else %>
					<%=link_to add_friends_path(user: current_user, friend: frnd), method: :post do %><button type="button" class="btn btn-xs btn-success"><i class="fa fa-user-plus"></i> &nbsp;Add As Friend</button><% end %>
				<% end %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/friends/_frndresult.js.erb
$('#results').html("<%= j (render 'friends/frndresult.html')%>")

app/views/friends/_partmodel.html.erb
<%if obj %>
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h2 class="modal-title" id="exampleModalLabel">
					 <% if obj.has_image? %>
							<%= image_tag(obj.images.last.picture.url, size: "40x40") %>
					<% else %>
							<%= image_tag("default.jpg", size: "40x40")%>
					<% end %><%= obj.fullName%> 
				</h2>
			</div>
			<div class="modal-body">
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>
				<button type="button" class="btn btn-primary" disabled = true>
					Send message<small></small>
				</button>
			</div>
		</div>
	</div>
<% end %>

app/views/friends/_result.html.erb
<% if params[:action] == 'search'%>
	<div class="result-flash-block col-md-12">
		<%= bootstrap_flash %>
	</div>
<% end %>
<% if @users %>
	<% @users.each do |frnd|%>
		<% if frnd != current_user %>
			<div class="well col-md-3 padclass">
				<b><i class="fa fa-user"></i> <br /><%= frnd.fullName%></b>
				<br />
				<%if current_user.friends.include?(frnd)%>
					<button type="button" class="btn btn-xs btn-default disabled"><i class="fa fa-user-plus"></i> &nbsp;Aleard Friends</button>
				<% else %>
					<%=link_to add_friends_path(user: current_user, friend: frnd) do %><button type="button" class="btn btn-xs btn-success"><i class="fa fa-user-plus"></i> &nbsp;Add As Friend</button><% end %>
				<% end %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/friends/_search_friends.html.erb
<div id="stock-lookup">
	<%= form_tag search_friend_path ,remote: true, method: :get ,id: "friend-lookup-form" do%>
		<div class="form-group row no-padding text-center col-md-12">
			<div class="col-md-6">
				<%= text_field_tag :friend, params[:friend], placeholder:"Enter name or email", autofocus: true, class: "form-control search-box input-xs"%>
			</div>
			<div class="col-md-1">
				<%= button_tag(type: :submit, class:"btn btn-sl btn-success cleantext") do%>
				<i class="fa fa-search"></i>
				<% end %>
			</div>
		</div>
	<% end %>
	
	<div id="results">
		<%= render 'friends/frndresult'%>	
	</div>
</div>