config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => "user/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'settings', to: 'welcome#setting'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  resources :user_stocks, only: [:create, :destroy, :index]
  resources :friendships
  resources :users, only:[:show]
  post 'add_friends',to: 'users#add_friend'
  get 'my_friends', to: 'users#my_friends'
  post 'accept_request', to: 'users#accept_request'
  post 'reject_request', to: 'users#reject_request'
  resources :profiles, only: [:create,:update,:edit,:new]
  resources :educations, only:[:create,:update,:edit,:new]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  
  has_many :friendships
  has_many :friends, through: :friendships
  
  has_one :profile, dependent: :destroy
  
  has_many :images
  
  def fullName
    return "#{f_name}" +" "+ "#{l_name}".strip if (f_name || l_name)
    "Anonymous" 
  end
  
  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    puts "stock"
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def stock_limit?
    (user_stocks.count < 10)
  end
  
  def can_add_stock?(ticker_symbol)
    puts stock_already_added?(ticker_symbol)
    !stock_already_added?(ticker_symbol) && stock_limit?
  end
  
  def has_image?
    !!images.last
  end
  
  def pending_task
    friendships.where(status: 'P').ids
  end
  
  def self.search(param)
    param.strip!
    param.downcase!
    to_stock_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_stock_back
    to_stock_back
  end
  
  def self.first_name_matches(param)
    matches('f_name',param)
  end
  
  def self.last_name_matches(param)
    matches('l_name',param)
  end
  
  def self.email_matches(param)
    matches('email',param)
  end
  
  def self.matches(field_name, param)
    User.where("#{field_name} like?", "%#{param}%")
  end
  
  def not_friend_with?(friend_id)
    self.friendships.where(friend_id: friend_id) < 1
  end
  
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:f_name, :l_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:f_name, :l_name])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def my_portfolio
    
  end
  
  def my_friends
    
  end
  
  def add_friend
    @friend = User.find(params[:friend])
    # current_user.friendships.build(friend_id: @friend.id)
    
    sql = "INSERT INTO `friendships` (`user_id`, `friend_id`, `created_at`, `updated_at`,`status`) VALUES ("+@friend.id.to_s+", "+current_user.id.to_s+",current_time(),current_time(),'P')"
    ActiveRecord::Base.connection.execute(sql)
    
    flash[:success] ="Your request has been sent to "+@friend.fullName
    
    redirect_to settings_path
  end
  
  def accept_request
    @friend = User.find(params[:friend])
    # current_user.friendships.build(friend_id: @friend.id)
    
    sql = "INSERT INTO `friendships` (`user_id`, `friend_id`, `created_at`, `updated_at`,`status`) VALUES ("+@friend.id.to_s+", "+current_user.id.to_s+",current_time(),current_time(),'A')"
    ActiveRecord::Base.connection.execute(sql)
    
    sql = "UPDATE friendships set status= 'A' where friend_id = "+@friend.id.to_s+" and user_id = "+current_user.id.to_s
    ActiveRecord::Base.connection.execute(sql)
    
    flash[:success] = @friend.fullName+" And you are friends now"
    
    redirect_to root_path
  end
  
  def reject_request
    
    @friendship = current_user.friendships.where(friend_id:params[:friend])
    @friendship.destroy(@friendship.ids)
    flash[:success] ="You rejectes "+User.find(params[:friend]).fullName+" friend request!!" 
    redirect_to root_path
  end
  
  def search
    if params[:friend].blank?
      flash.now[:danger] ="You have entered an empty string"
    else
      @users = User.search(params[:friend])
      flash.now[:danger] ="No such user found !!" if @users.blank?
    end
    respond_to do |format|
         format.js{ render partial: 'friends/frndresult' }          
    end
  end
  
end

app/views/users/_friends.html.erb
<% content_for :content do %>
	<div id="results">
				<%= render 'users/result'%>	
	</div>
	<h3> My Friends</h3>
	<%if obj.size > 0 %>
		<div class="row-lg-8">
			<% obj.each_with_index do |frndship, index|%>
				<%frnd = User.find(frndship.friend_id) %>
				<div class="card">
					<div class="card">
						<div class="card-header" id="headingTwo">
							<h5 class="mb-0">
								<% if frnd.has_image? %>
									<%= image_tag(frnd.images.last.picture.url, size: "40x40") %>
								<% else %>
									<%= image_tag("default.jpg", size: "40x40")%>
								<% end %>
								<button type="button" class="btn btn-link btn-md" data-toggle="modal" data-target="#exampleModal<%=index%>" data-whatever="@mdo"><%=frnd.fullName %></button>
								<!-- <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse<%=index%>" aria-expanded="false" aria-controls="collapseTwo"><%=frnd.fullName %></button> -->
							</h5>
						</div>
						<!-- <div id="collapse<%=index%>" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
							<div class="card-body">
								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Open modal for @mdo</button>
								<%=link_to add_friends_path(user: current_user, friend: frnd) do %><button type="button" class="btn btn-xs btn-success"><i class="fa fa-user-plus"></i> &nbsp;Go to profile</button><% end %>
							</div>
						</div> -->
					</div>
				</div>
				<div class="modal fade" id="exampleModal<%=index%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  					<%=render 'friends/partmodel' , obj: frnd%>
				</div>
			<% end %>
		</div>
	<% else %>
		<div class="col-lg-8" style="color: red">
				<p>You don't have any friend yet. Please add some.</p>
		</div>
	<% end %>
<% end %>

<h3> Search friend</h3>
<div class="row">
	<div class="col-sl-12">
		<%= render 'friends/search_friends'%>
	</div>
</div>
<h3>Friend Suggestion</h3>
<div class="row col-lg-12">
	<% User.all.each do |frnd|%>
		<%if frnd != current_user%>
		<div class="well col-md-4 padclass">
			<b>
				<% if frnd.has_image? %>
						<%= image_tag(frnd.images.last.picture.url, size: "40x40") %>
				<% else %>
						<%= image_tag("default.jpg", size: "40x40")%>
				<% end %><%= frnd.fullName%>
			</b>
			<br />
			<% if obj.size > 0 && obj.include?(frnd) %>
				<button type="button" class="btn btn-xs btn-default disabled"><i class="fa fa-user-plus"></i> &nbsp;Aleard Friends</button>
			<% else %>
				<%=link_to add_friends_path(user: current_user, friend: frnd), method: :post do %><button type="button" class="btn btn-xs btn-success"><i class="fa fa-user-plus"></i> &nbsp;Add As Friend</button><% end %>
			<% end %>
		</div>
		<% end %>
	<% end %>
	</div>

app/views/users/_profile.html.erb
<br />
<div class="col-md-4">
	<h3><%= obj.fullName %></h3>
	<div class="card">
		<%if imgae_exist? %>
			<%= image_tag(current_user.images.last.picture.url, size: "300x300",:class=> "img-circular") if current_user.images.last.picture? %>
		<% else %>
			<%= image_tag("default.jpg", size: "300x300",:class=> "img-circular")%>
		<% end %>
	  <div class="card-body">
	    <h5 class="card-title"><%=link_to "Edit profile image",new_image_path%></h5>
	    <h5 class="card-title"><%=link_to "Edit Personal Details",edit_user_registration_path%></h5>
	    <!-- <%=link_to "Edit Personal Details", edit_user_registration_path, class: "btn btn-primary",style: "color:white;"%> -->
	  </div>
	</div>
</div>
<div class="col-md-6">
	<div class="card">
	  <div class="card-body">
	    <%if profile_exist? %>
		    <div>
		    	<h3 class="card-title">Personal Details<br /></h3>
		    	<table>
		    		<tr><td><b>Company : </b></td><td><%=obj.profile.company%></td></tr>
		    		<tr><td><b>Designation : </b></td><td><%=obj.profile.profession%></td></tr>
		    		<tr><td><b>Currently In : </b></td><td><%=obj.profile.temp_address%></td></tr>
		    		<tr><td><b>Belongs from : </b></td><td><%=obj.profile.fixed_address%></td></tr>
		    	</table>
		    </div>
		    <div style="float: right;"><%=link_to "Edit", edit_profile_path(obj.profile.id)%></div>
		    <hr />
		    <div>
		    	<p class="card-text"><h3>Education</h3> 
			    	<ul style="list-style: none;">
			    		<%obj.profile.educations.each do |edu|%>
			    			<li><b><%=edu.standard%></b><small>(<%=edu.start+" - "+edu.end%>)</small><br />
			    				<%= edu.school_college%> <%= edu.from_where%> <%= edu.university%>
			    				<small><b> Subjects - </b>(<%=edu.subjects%>) </small></li>
			    		<% end %>
			    	</ul>
			    </p>
		    </div>
		    <div style="float: right;"><%=link_to "Edit", obj.profile.educations.size > 0 ? edit_education_path(obj.profile.id) : new_education_path %></div>
		    <hr />
		<% else %>
			<p class="card-text"><b><%=link_to "Please Update your profile" , new_profile_path%></b></p>
	    <% end %>
	  </div>
	</div>
</div>
<%= render 'layouts/stocksdetails'%>
<!-- <div class="col-lg-12" style="border: 1px solid black;">
	<div class="col-md-5">
		<%= render 'layouts/stocksdetails'%>
	</div>
	<div class="col-md-4">
		<div id="results">
			<%= render 'users/result'%>	
		</div>
	</div>
</div> -->

app/views/users/_result.html.erb
<% if params[:action] == 'search'%>
	<div class="result-flash-block col-md-12">
		<%= bootstrap_flash %>
	</div>
<% end %>
<% if @stock %>
	<div class="well col-md-12">
		<h3><strong>Company Name : </strong><%=@stock.name%><small>(<%=@stock.ticker%>)</small><br />
		<strong>Last price : </strong><%=@stock.last_price%><br />
		<strong>Highest : </strong><%=@stock.highest%><br />
		<strong>Lowest : </strong><%=@stock.lowest%><br />
		<% if current_user.can_add_stock?(@stock.ticker) %>
			<%= link_to "Add To Stock" ,user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class:"btn btn-xs btn-success", method: :post%>
		<% else %>
			<span class="label label-xs label-default">
				Already added
				<%if !current_user.stock_limit? %> 
					10 stocks.
				<% end %>
				<%if current_user.stock_already_added?(@stock.ticker) %> 
					this stock.
				<% end %>
			</span>
		<% end %>
	</div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html')%>")

app/views/users/my_friends.html.erb
<%= render 'users/friends', obj: @friendship %>
	

app/views/users/my_portfolio.html.erb
<h2>Search for stock</h2>
<div id="stock-lookup">
	<%= form_tag search_stock_path ,remote: true, method: :get ,id: "stock-lookup-form" do%>
	<div class="form-group row no-padding text-center col-md-12">
		<div class="col-md-9">
			<%= text_field_tag :stock, params[:stock], placeholder:"Stock ticker symbol", autofocus: true, class: "form-control search-box input-lg"%>
		</div>
		<div class="col-md-2">
			<%= button_tag(type: :submit, class:"btn btn-lg btn-success cleantext") do%>
			<i class="fa fa-search"></i> Lookup stock
			<% end %>
		</div>
	</div>
	<% end %>
</div>
<div id="results">
	<%= render 'users/result'%>	
</div>

<% if logged_in?  %>
	<%= render 'layouts/stocksdetails'%>
<% end %>