config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => "user/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'settings', to: 'welcome#setting'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  resources :user_stocks, only: [:create, :destroy, :index]
  resources :friendships
  resources :users, only:[:show]
  post 'add_friends',to: 'users#add_friend'
  get 'my_friends', to: 'users#my_friends'
  post 'accept_request', to: 'users#accept_request'
  post 'reject_request', to: 'users#reject_request'
  resources :profiles, only: [:create,:update,:edit,:new]
  resources :educations, only:[:create,:update,:edit,:new]
end

app/views/layouts/_stocksdetails.html.erb
<div class="col-lg-12">
	<div class="col-lg-12">
		<h4>Stocks tracked by you </h4>
		<br />
		<table class="table col-lg-12">
			<% current_user.stocks.each do |us|%>
			<tr>
				<td>
					<%=link_to search_stock_path(stock: us.ticker), remote: true  do %>
					<b><%= us.name.upcase %><small>(<%= us.ticker%>)</small></b><br />
					<% end %>
				</td>
				<td>
					<i class="fa fa-arrow-up" style="color: green;"></i> <%= us.highest%>
				</td>
				<td>
					<i class="fa fa-arrow-down" style="color: red;"></i> <%= us.lowest%>
				</td>
			</tr>
			<% end %>
		</table>
		<div class="col-lg-12">
				<div>  Highest <i class="fa fa-arrow-up" style="color: green;"></i>  &nbsp;&nbsp;&nbsp; Lowest &nbsp;<i class="fa fa-arrow-down" style="color: red;"></i></div>
				<br />
				<%= link_to user_stocks_path do |btn|%>
					<button class="btn btn-success"> <i class="fa fa-wrench"></i> Manage Stock </button>
				<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StockManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static">
      <div class="containt" style="margin-right: 10px;">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %><b class="navbar-brand " style="color: black;"><i class="fa fa-bar-chart" aria-hidden="true" style="color: green;"></i> Stock&nbsp;&nbsp;Management</b><% end %>
        <div class="collapse navbar-collapse js-navbar-collapse">
        <% if logged_in?%>
			<ul class="nav navbar-nav">
				<li>
					<a href="#"></a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right ">
				<li>
					<h4 class="comman"> 
						<%if imgae_exist? %>
							<%= image_tag(current_user.images.last.picture.url, size: "30x30") if current_user.images.last.picture? %>
						<% else %>
							<%= image_tag("default.jpg", size: "30x30")%>
						<% end %>
					<%= current_user.fullName %>
					</h4>
				</li>
				<li class="dropdown" style="padding-left: 20px;">
					<h3><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user comman"></i> <span class="caret comman"></span></a>
					<ul class="dropdown-menu scrollable-menu" style="background-color: #cccccc;">
						<li>
							<%= link_to "Stockes", my_portfolio_path%>
						</li>
						<li role="separator" class="divider"></li>
						<li>
							<%= link_to "Settings", settings_path%>
						</li>
						<li>
							<%= link_to "Messages", "#" %>
						</li>
						<li role="separator" class="divider"></li>
						<li>
							<%= link_to "Logout", destroy_user_session_path, method: :delete %>
						</li>
					</ul></h3>
				</li>
				<%if current_user.pending_task.count > 0 %>
					<li class="dropdown dropdown-large" >
						  <button class="btn btn-default btn-lg btn-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						    <span class="glyphicon glyphicon-comment"></span>
						  </button>
						  <span class="badge badge-notify"><%=current_user.pending_task.count%></span>
						  <ul class="dropdown-menu scrollable-menu" style="background-color: #cccccc; width: 300px;padding-left: 20px;padding-right: 20px;" >
						  	<h4><b>Friend Requests</b></h4>
						  	<% current_user.pending_task.each do |task|%>
						  		<% frnd = User.find(Friendship.find(task.to_s).friend_id) %>
						  		<li style="color: black; margin-bottom: 40px;">
						  			<div >
						  				<h4><% if frnd.has_image? %>
											<%= image_tag(frnd.images.last.picture.url, size: "40x40") %>
										<% else %>
											<%= image_tag("default.jpg", size: "40x40")%>
										<% end %><%= frnd.fullName %></h4>
										<div style="margin: 10px;">
											<div style="float: left"><%=link_to accept_request_path(friend: frnd), method: :post do  %><button class="btn btn-xs btn-success">Accept</button><% end %></div>
											<div style="float: right"><%=link_to reject_request_path(friend: frnd), method: :post do  %><button class="btn btn-xs btn-danger">Reject</button><% end %></div>
										</div>
						  			</div>
								</li>
								<li role="separator" class="divider"></li>
						  	<% end %>
						</ul>
					</li>
				<% end %>
				<!-- <li class="col-md-4"></li> -->
			</ul>
		<% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-md-4">
        	<div id="content"><%= content_for?(:content) ? yield(:content) : "" %></div>
		</div>
      </div><!--/row-->
	
      <!-- <footer>
        <p>&copy; Company 2019</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>